apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-canary
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris-canary
  template:
    metadata:
      labels:
        app: tetris      # ← SHARED service selector
        version: v7
    spec:
      containers:
      - name: tetris
        image: surendrak17/tetrisv1:7
        ports:
        - containerPort: 3000

        #kubectl scale deployment tetris-canary --replicas=1 -- Command to scale up the pods for replica based approach 
